### DISCUSSION TITLE
Запуск образа NCANode в kubernetes

### DISCUSSION THREAD

**Discussion by ainenya** [malikzh/NCANode#141] [Q&A] [answered]
Добрый день, столкнулся с проблемой при запуске образа `malikzh/ncanode:3.2.0` в kubernetes.
При локальном развертывании в docker всё нормально, web-сервер успешно запускается и работает.

При запуске в kubernetes приложение падает с ошибкой (уровень логирования debug):
[ncanode(1).log](https://github.com/malikzh/NCANode/files/9747904/ncanode.1.log)

Deployment описан минимально: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ncanode
  labels:
    app.kubernetes.io/name: ncanode
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ncanode
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ncanode
    spec:
      hostname: ncanode
      containers:
      - name: ncanode
        image: malikzh/ncanode:3.2.0
        command:
          - java
        args:
          - -jar
          - NCANode.jar
          - --debug
        ports:
        - containerPort: 14579
        volumeMounts:
        - mountPath: /cache
          name: ncanode-cache
      volumes:
      - name: ncanode-cache
        emptyDir: {}
```

Хотел узнать запускал ли кто-то NCANode в k8s и что для этого требуется?

**Comment by malikzh** [comment, marked as answer]
Попробуйте добавить env:

```
NCANODE_PORT=14579
```

Насколько я понял, некорректно передается порт: 

```
Caused by: java.lang.NumberFormatException: For input string: "tcp://172.21.202.110:14579"
```

Судя, по логам.

**Reply by ainenya** [reply]
Спасибо, помогло. Поделюсь здесь конечным вариантом деплоймента, если кто-то ещё столкнётся с данной проблемой:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ncanode
  labels:
    app.kubernetes.io/name: ncanode
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ncanode
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ncanode
    spec:
      containers:
      - name: ncanode
        image: malikzh/ncanode:3.2.0
        env:
          - name: NCANODE_PORT
            value: "14579"
        command:
          - java
        args:
          - -jar
          - NCANode.jar
          - --debug
        ports:
        - containerPort: 14579
        volumeMounts:
        - mountPath: /cache
          name: ncanode-cache
      volumes:
      - name: ncanode-cache
        emptyDir: {}
```

Версия k8s: 1.22.10

Debug-лог ругается на переменную окружения NCANODE_PORT типа string (технически, все environment variables являются строками, поэтому это странно), но приложение запускается корректно.
